GH-2 Improve reporting fatal errors
For example, when the users provides an input that doesn't exist,
the error changed from

```
Failed to locate input /home/user/Downloads/lego-racers/1, does it exists?. The error is Os { code: 2, kind: NotFound, message: "No such file or directory" }
Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

to

```
Error:
   0: Unable to locate input file
   1: No such file or directory (os error 2)

Suggestion: verify that /home/user/Downloads/lego-racers/1 exists and is readable.
```